# This file is autogenerated by emkyoot
# See emkyoot.generator.generate_device_bases()

from emkyoot.parameters import (
    NumericParameter,
    QueryableNumericParameter,
    SettableAndQueryableNumericParameter,
    EnumParameter,
    SettableEnumParameter,
    BinaryParameter,
    SettableToggleParameter,
    SettableAndQueryableToggleParameter,
    int_to_enum,
)

class DimmableLight:
    def __init__(self, arg0, arg1):
        self.state = SettableAndQueryableToggleParameter("state")
        self.brightness = SettableAndQueryableNumericParameter("brightness", arg0, arg1)


class LightWithColorTemp(DimmableLight):
    def __init__(self, arg0, arg1, arg2, arg3):
        DimmableLight.__init__(self, arg0, arg1)
        self.color_temp = SettableAndQueryableNumericParameter("color_temp", arg2, arg3)


__all__ = [
    'LightWithColorTemp',
    'DimmableLight',
    ]
