# This file is autogenerated by emkyoot
# See emkyoot.generator.generate_device_bases()

from emkyoot.parameters import (
    NumericParameter,
    QueryableNumericParameter,
    SettableAndQueryableNumericParameter,
    EnumParameter,
    SettableEnumParameter,
    BinaryParameter,
    SettableToggleParameter,
    SettableAndQueryableToggleParameter,
    int_to_enum,
)

class DimmableLight:
    def __init__(self, min0, max1):
        self.state = SettableAndQueryableToggleParameter("state")
        self.brightness = SettableAndQueryableNumericParameter("brightness", min0, max1)


class LightWithColorTemp(DimmableLight):
    def __init__(self, min0, max1, min2, max3):
        DimmableLight.__init__(self, min0, max1)
        self.color_temp = SettableAndQueryableNumericParameter("color_temp", min2, max3)


__all__ = [
    'LightWithColorTemp',
    'DimmableLight',
    ]
